import { StringKey } from './string-key.consts';

export const enMessages: Record<StringKey, string> = {
  // Login and Register
  [StringKey.LOGIN_TO_YOUR_ACCOUNT]: 'Log in to your account',
  [StringKey.SING_UP]: 'Sign Up',
  [StringKey.DONT_HAVE_AN_ACCOUNT]: "Don't have an account?",
  [StringKey.FORGOT_PASSWORD]: 'Forgot Password',
  [StringKey.FORGOT_PASSWORD_DESCRIPTION]:
    "No worries, it happens! Enter your email address and we'll send you a code to reset your password.",
  [StringKey.BACK]: 'Back',
  [StringKey.CREATE_YOUR_ACCOUNT]: 'Create your account',
  [StringKey.BUSINESS]: 'Business',
  [StringKey.OR]: 'or',
  [StringKey.CONTINUE_WITH_GOOGLE]: 'Continue with Google',
  [StringKey.ALREADY_HAVE_AN_ACCOUNT]: 'Already have an account?',
  [StringKey.SIGN_IN]: 'Sign In',
  [StringKey.ENTER_FOUR_DIGIT_CODE]: 'Enter the 4-digit code sent to',
  [StringKey.VERIFY_RESET_CODE]: 'Verify reset code',
  [StringKey.SET_NEW_PASSWORD]: 'Set new password',
  [StringKey.CHOOSE_A_STRONG_PASSWORD]: 'Choose a strong password for your account.',
  [StringKey.BACK_TO_REGISTER]: 'Back to registration',
  [StringKey.WE_SENT_FOUR_DIGIT_CODE]: 'We sent a 4-digit code to',
  [StringKey.ENTER_IT_BELOW_TO_ACTIVATE]: 'Enter it below to activate your account.',
  [StringKey.DIDNT_RECEIVE_THE_CODE]: "Didn't receive the code?",
  [StringKey.RESEND]: 'Resend',

  // Forgot Password Form
  [StringKey.EMAIL_ADDRESS]: 'Email Address',
  [StringKey.EMAIL_PLACEHOLDER]: 'hello@nomnomsave.com',
  [StringKey.SEND_RESET_CODE]: 'Send Reset Code',
  [StringKey.SENDING]: 'Sending…',
  [StringKey.BACK_TO_LOGIN]: '← Back to Login',
  [StringKey.ACCOUNT_NOT_FOUND]: 'Account not found.',
  [StringKey.ACCOUNT_NOT_FOUND_DESCRIPTION]: 'No account found for this email address.',
  [StringKey.FAILED_TO_SEND_RESET_CODE]: 'Failed to send reset code.',
  [StringKey.FAILED_TO_SEND_RESET_CODE_DESCRIPTION]:
    'Please check your email address and try again.',

  // Reset Password Form
  [StringKey.RESET_CODE]: 'Reset Code',
  [StringKey.RESET_CODE_ERROR]: 'Please enter the correct 4-digit code from your email.',
  [StringKey.VERIFYING]: 'Verifying…',
  [StringKey.VERIFY_CODE]: 'Verify Code',
  [StringKey.INVALID_CODE]: 'Invalid code.',
  [StringKey.INVALID_CODE_DESCRIPTION]: 'Please enter the full 4-digit code from your email.',
  [StringKey.INVALID_OR_EXPIRED_CODE]: 'Invalid or expired code.',
  [StringKey.INVALID_OR_EXPIRED_CODE_DESCRIPTION]: 'Please check the code and try again.',
  [StringKey.VERIFICATION_FAILED]: 'Verification failed.',
  [StringKey.VERIFICATION_FAILED_DESCRIPTION]: 'Something went wrong. Please try again.',
  [StringKey.NEW_PASSWORD]: 'New Password',
  [StringKey.CONFIRM_PASSWORD]: 'Confirm Password',
  [StringKey.PASSWORD_PLACEHOLDER]: '••••••••',
  [StringKey.HIDE_PASSWORD]: 'Hide password',
  [StringKey.SHOW_PASSWORD]: 'Show password',
  [StringKey.RESETTING]: 'Resetting…',
  [StringKey.RESET_PASSWORD]: 'Reset Password',
  [StringKey.PASSWORD_RESET_SUCCESS]: 'Password reset!',
  [StringKey.PASSWORD_RESET_SUCCESS_DESCRIPTION]: 'Your password has been changed. Please sign in.',
  [StringKey.RESET_FAILED]: 'Reset failed.',
  [StringKey.RESET_FAILED_DESCRIPTION]: 'Something went wrong. Please try again.',

  // Login Form
  [StringKey.LOGIN_EMAIL_PLACEHOLDER]: 'name@example.com',
  [StringKey.PASSWORD]: 'Password',
  [StringKey.FORGOT_PASSWORD_LINK]: 'Forgot Password?',
  [StringKey.SIGNING_IN]: 'Signing in…',
  [StringKey.LOGIN]: 'Login',
  [StringKey.INVALID_CREDENTIALS]: 'Invalid credentials.',
  [StringKey.INVALID_CREDENTIALS_DESCRIPTION]: 'Please check your email and password.',
  [StringKey.EMAIL_NOT_VERIFIED]: 'Email not verified.',
  [StringKey.EMAIL_NOT_VERIFIED_DESCRIPTION]: 'Please verify your email before signing in.',
  [StringKey.LOGIN_FAILED]: 'Login failed.',
  [StringKey.LOGIN_FAILED_DESCRIPTION]: 'Something went wrong. Please try again.',

  // Login Left Panel
  [StringKey.WELCOME_BACK]: 'Welcome Back',
  [StringKey.FEATURE_DISCOUNTS]: '70% Discounts on Surplus',
  [StringKey.FEATURE_REAL_TIME]: 'Real-time Local Offers',
  [StringKey.FEATURE_MAP]: 'Premium Map Access',
  [StringKey.LOGIN_TAGLINE]: 'Saving the planet, one delicious bite at a time.',

  // Registration Forms (shared)
  [StringKey.CREATING_ACCOUNT]: 'Creating account…',
  [StringKey.CREATE_ACCOUNT]: 'Create Account',
  [StringKey.EMAIL_ALREADY_IN_USE]: 'Email already in use.',
  [StringKey.EMAIL_ALREADY_IN_USE_DESCRIPTION]: 'An account with this email already exists.',
  [StringKey.REGISTRATION_FAILED]: 'Registration failed.',
  [StringKey.REGISTRATION_FAILED_DESCRIPTION]: 'Something went wrong. Please try again.',
  [StringKey.AGREEMENT_REQUIRED]: 'Agreement required.',
  [StringKey.AGREEMENT_REQUIRED_DESCRIPTION]:
    'You must agree to the Terms of Service and Privacy Policy to continue.',
  [StringKey.REGISTRATION_FIELDS_ERROR]: 'Please check the form fields.',
  [StringKey.BY_JOINING_AGREE]: 'By joining, you agree to our',
  [StringKey.TERMS_OF_SERVICE]: 'Terms of Service',
  [StringKey.AND]: 'and',
  [StringKey.PRIVACY_POLICY]: 'Privacy Policy',

  // Business Form
  [StringKey.BUSINESS_NAME]: 'Business Name',
  [StringKey.BUSINESS_NAME_PLACEHOLDER]: 'Nom Nom Store',
  [StringKey.BUSINESS_EMAIL_PLACEHOLDER]: 'cafe@example.com',
  [StringKey.STORE_ADDRESS]: 'Store Address',
  [StringKey.STORE_ADDRESS_PLACEHOLDER]: '123 Main St, Kyiv, Ukraine',

  // Buyer Form
  [StringKey.FULL_NAME]: 'Full Name',
  [StringKey.FULL_NAME_PLACEHOLDER]: 'Boss Molokosos',
  [StringKey.BUYER_EMAIL_PLACEHOLDER]: 'john@example.com',

  // Registration Left Panel
  [StringKey.JOIN_COMMUNITY_BUYER]: 'Join the community',
  [StringKey.JOIN_COMMUNITY_BUSINESS]: 'Join the community saving food every day',
  [StringKey.FEATURE_DISCOUNTS_SHORT]: '70% Discounts',
  [StringKey.FEATURE_REAL_TIME_SHORT]: 'Real-time offers',

  // Verify Email Left Panel
  [StringKey.ALMOST_THERE_LINE1]: 'Almost',
  [StringKey.ALMOST_THERE_LINE2]: 'there!',
  [StringKey.VERIFY_EMAIL_LEFT_PANEL_DESCRIPTION]:
    "Check your inbox - we've sent a 4-digit code to confirm your email address.",

  // Verify Email Form
  [StringKey.EMAIL_VERIFIED]: 'Email verified!',
  [StringKey.ACCOUNT_IS_READY]: 'Your account is ready. Please sign in.',
  [StringKey.VERIFICATION_CODE]: 'Verification Code',
  [StringKey.VERIFY_EMAIL_CODE_ERROR]: 'Please enter the correct 4-digit code from your email.',
  [StringKey.VERIFYING_EMAIL]: 'Verifying…',
  [StringKey.VERIFY_EMAIL]: 'Verify Email',
  [StringKey.INVALID_CODE_SHORT]: 'Invalid code.',
  [StringKey.INVALID_CODE_SHORT_DESCRIPTION]: 'Please enter the full 4-digit code.',

  // Authentication Validation
  [StringKey.VALID_EMAIL]: 'Please enter a valid email address',
  [StringKey.PASSWORD_REQUIRED]: 'Password is required',
  [StringKey.PASSWORD_MIN]: 'Password must be at least 8 characters',
  [StringKey.PASSWORD_MAX]: 'Password must be less than 100 characters',
  [StringKey.PASSWORDS_DO_NOT_MATCH]: 'Passwords do not match',
  [StringKey.BUSINESS_NAME_MIN]: 'Business name must be at least 2 characters',
  [StringKey.BUSINESS_NAME_MAX]: 'Business name must be less than 100 characters',
  [StringKey.ADDRESS_MIN]: 'Please enter a valid address',
  [StringKey.ADDRESS_MAX]: 'Address must be less than 200 characters',
  [StringKey.AGREE_TO_TERMS_REQUIRED]:
    'You must agree to the Terms of Service and Privacy Policy to continue.',
  [StringKey.FULL_NAME_MIN]: 'Full name must be at least 2 characters',
  [StringKey.FULL_NAME_MAX]: 'Full name must be less than 100 characters',
  [StringKey.CODE_LENGTH]: 'Code must be 4 digits',
  [StringKey.CODE_DIGITS_ONLY]: 'Code must contain digits only',

  // Establishment Navbar
  [StringKey.TEMPLATES]: 'Templates',
  [StringKey.MENU]: 'Menu',
  [StringKey.SETTINGS]: 'Settings',
  [StringKey.ANALYTICS]: 'Analytics',
  [StringKey.LOGOUT]: 'Log out',
  [StringKey.QUICK_SEARCH]: 'Quick search...',

  // Templates Page
  [StringKey.NEW_PRODUCT]: 'New Product',
  [StringKey.NEW_BOX]: 'New Box',
  [StringKey.PRODUCTS]: 'Products',
  [StringKey.BOXES]: 'Boxes',
  [StringKey.ALL_TYPES]: 'All types',
  [StringKey.NO_IMAGE]: 'No image',
  [StringKey.EDIT]: 'Edit',
  [StringKey.PUBLISH]: 'Publish',
  [StringKey.DELETE]: 'Delete',
  [StringKey.PUBLISHED]: 'Published',
  [StringKey.DRAFT]: 'Draft',
  [StringKey.QTY]: 'Qty',
  [StringKey.EXP]: 'Exp',
  [StringKey.NO_PRODUCTS]: 'No products yet',
  [StringKey.CREATE_FIRST_PRODUCT]: 'Create your first product template to get started.',
  [StringKey.NO_BOXES]: 'No boxes yet',
  [StringKey.CREATE_FIRST_BOX]: 'Create your first box template to get started.',

  // Product/Box Dialog
  [StringKey.CREATE_PRODUCT]: 'Create Product',
  [StringKey.EDIT_PRODUCT]: 'Edit Product',
  [StringKey.CREATE_BOX]: 'Create Box',
  [StringKey.EDIT_BOX]: 'Edit Box',
  [StringKey.NAME]: 'Name',
  [StringKey.DESCRIPTION]: 'Description',
  [StringKey.ORIGINAL_PRICE]: 'Original Price',
  [StringKey.QUANTITY]: 'Quantity',
  [StringKey.PRODUCT_TYPE]: 'Product Type',
  [StringKey.BOX_TYPE]: 'Box Type',
  [StringKey.SELECT_TYPE]: 'Select type',
  [StringKey.EXPIRATION_DATE]: 'Expiration Date',
  [StringKey.SAVING]: 'Saving…',
  [StringKey.SAVE_CHANGES]: 'Save Changes',
  [StringKey.PRODUCT_CREATED]: 'Product created successfully!',
  [StringKey.PRODUCT_UPDATED]: 'Product updated successfully!',
  [StringKey.BOX_CREATED]: 'Box created successfully!',
  [StringKey.BOX_UPDATED]: 'Box updated successfully!',
  [StringKey.FAILED_TO_CREATE_PRODUCT]: 'Failed to create product.',
  [StringKey.FAILED_TO_UPDATE_PRODUCT]: 'Failed to update product.',
  [StringKey.FAILED_TO_CREATE_BOX]: 'Failed to create box.',
  [StringKey.FAILED_TO_UPDATE_BOX]: 'Failed to update box.',

  // Publish Dialog
  [StringKey.PUBLISH_TO_MENU]: 'Publish to Menu',
  [StringKey.PUBLISHING_ITEM]: 'Publishing item',
  [StringKey.DISCOUNT_PRICE]: 'Discount Price',
  [StringKey.START_TIME]: 'Start Time',
  [StringKey.END_TIME]: 'End Time',
  [StringKey.PUBLISHING]: 'Publishing…',
  [StringKey.PUBLISHED_TO_MENU]: 'Published to menu successfully!',
  [StringKey.FAILED_TO_PUBLISH]: 'Failed to publish to menu.',

  // Delete Dialog
  [StringKey.CONFIRM_DELETE]: 'Confirm Delete',
  [StringKey.DELETE_CONFIRMATION]: 'Are you sure you want to delete',
  [StringKey.CANCEL]: 'Cancel',
  [StringKey.DELETING]: 'Deleting…',
  [StringKey.DELETED_SUCCESSFULLY]: 'Deleted successfully!',
  [StringKey.FAILED_TO_DELETE]: 'Failed to delete.',

  // Validation (establishment)
  [StringKey.ITEM_NAME_MIN]: 'Name must be at least 2 characters',
  [StringKey.ITEM_NAME_MAX]: 'Name must be less than 100 characters',
  [StringKey.DESCRIPTION_MIN]: 'Description must be at least 10 characters',
  [StringKey.DESCRIPTION_MAX]: 'Description must be less than 500 characters',
  [StringKey.PRICE_POSITIVE]: 'Price must be greater than 0',
  [StringKey.EXPIRATION_REQUIRED]: 'Expiration date is required',
  [StringKey.QUANTITY_MIN]: 'Quantity must be at least 1',
  [StringKey.START_TIME_REQUIRED]: 'Start time is required',
  [StringKey.END_TIME_REQUIRED]: 'End time is required',
  [StringKey.END_TIME_AFTER_START]: 'End time must be after start time',
  [StringKey.CLOSE_TIME_AFTER_OPEN]: 'Closing time must be after opening time',

  // Menu Page
  [StringKey.STATUS_ACTIVE]: 'Active',
  [StringKey.STATUS_SOLD_OUT]: 'Sold Out',
  [StringKey.STATUS_INACTIVE]: 'Inactive',
  [StringKey.ALL_STATUSES]: 'All statuses',
  [StringKey.ACTIVE_ITEMS]: 'active',
  [StringKey.SOLD_OUT_ITEMS]: 'sold out',
  [StringKey.INACTIVE_ITEMS]: 'inactive',
  [StringKey.AVAILABLE]: 'Available',
  [StringKey.PAUSE]: 'Pause',
  [StringKey.RESUME]: 'Resume',
  [StringKey.DEACTIVATE]: 'Deactivate',
  [StringKey.EDIT_MENU_ITEM]: 'Edit Menu Item',
  [StringKey.ITEM_PAUSED]: 'Item paused.',
  [StringKey.ITEM_RESUMED]: 'Item resumed.',
  [StringKey.ITEM_DEACTIVATED]: 'Item deactivated.',
  [StringKey.MENU_ITEM_UPDATED]: 'Menu item updated.',
  [StringKey.FAILED_TO_UPDATE_STATUS]: 'Failed to update status.',
  [StringKey.FAILED_TO_UPDATE_MENU_ITEM]: 'Failed to update menu item.',
  [StringKey.NO_MENU_ITEMS]: 'No menu items yet',
  [StringKey.PUBLISH_FROM_TEMPLATES]: 'Publish items from Templates to see them here.',
  [StringKey.UPDATING]: 'Updating…',

  // Settings Page
  [StringKey.PROFILE_INFORMATION]: 'Profile Information',
  [StringKey.WORKING_HOURS]: 'Working Hours',
  [StringKey.CHANGE_PASSWORD]: 'Change Password',
  [StringKey.DELETE_ACCOUNT]: 'Delete Account',
  [StringKey.DELETE_ACCOUNT_WARNING]:
    'Once you delete your account, there is no going back. This action is permanent.',
  [StringKey.PHONE]: 'Phone',
  [StringKey.PROFILE_UPDATED]: 'Profile updated successfully!',
  [StringKey.FAILED_TO_UPDATE_PROFILE]: 'Failed to update profile.',
  [StringKey.CURRENT_PASSWORD]: 'Current Password',
  [StringKey.COMING_SOON]: 'Coming Soon',
  [StringKey.SAVE_HOURS]: 'Save Hours',
  [StringKey.HOURS_UPDATED]: 'Working hours updated!',
  [StringKey.FAILED_TO_UPDATE_HOURS]: 'Failed to update working hours.',
  [StringKey.CLOSED]: 'Closed',
  [StringKey.MONDAY]: 'Monday',
  [StringKey.TUESDAY]: 'Tuesday',
  [StringKey.WEDNESDAY]: 'Wednesday',
  [StringKey.THURSDAY]: 'Thursday',
  [StringKey.FRIDAY]: 'Friday',
  [StringKey.SATURDAY]: 'Saturday',
  [StringKey.SUNDAY]: 'Sunday',

  // Impact Stats
  [StringKey.MEALS_SAVED]: 'Meals Saved',
  [StringKey.CO2_PREVENTED]: 'CO₂ Prevented',
  [StringKey.REVENUE_GENERATED]: 'Revenue Generated',
  [StringKey.BAGS_SOLD]: 'Bags sold',
  [StringKey.FOOD_SAVED]: 'Food saved',
  [StringKey.YOUR_IMPACT]: 'Your Impact',

  // Templates Page (additional)
  [StringKey.TEMPLATES_LIBRARY]: 'Templates Library',
  [StringKey.TEMPLATES_LIBRARY_DESCRIPTION]:
    'Manage reusable products and Magic Boxes. Publish them to your menu with one click.',
  [StringKey.MAGIC_BOXES]: 'Magic Boxes',
  [StringKey.REC_PRICE]: 'Rec. price',
  [StringKey.MENU_PRICE]: 'Menu price',
  [StringKey.PUBLISH_TO_MENU_BTN]: 'Publish to Menu',

  // Menu Page (additional)
  [StringKey.ACTIVE_MENU]: 'Active Menu',
  [StringKey.ACTIVE_MENU_DESCRIPTION]: 'Items currently published and visible to customers.',
  [StringKey.PICKUP_WINDOW]: 'Pickup window',
  [StringKey.DISCOUNT]: 'Discount',
  [StringKey.OFF]: 'off',

  // Working Hours Table
  [StringKey.DAY]: 'Day',
  [StringKey.OPENS]: 'Opens',
  [StringKey.CLOSES]: 'Closes',
  [StringKey.OPEN]: 'Open',
  [StringKey.TODAY]: 'Today',

  // Shared Access Key
  [StringKey.SHARED_ACCESS_KEY]: 'Shared Access Key',
  [StringKey.SHARED_ACCESS_KEY_DESCRIPTION]:
    'Other establishments with this key can access your products and boxes. Set to "0" to make them fully public.',
  [StringKey.MAKE_PUBLIC]: 'Make publicly available',
  [StringKey.MAKE_PUBLIC_DESCRIPTION]: 'Any establishment can access this item (key set to "0")',
  [StringKey.ACCESS_KEY_LABEL]: 'Access Key',
  [StringKey.KEY_UPDATED]: 'Access key updated',
  [StringKey.FAILED_TO_UPDATE_KEY]: 'Failed to update access key',
  [StringKey.EDIT_KEY]: 'Edit key',

  // Multi-select
  [StringKey.ALL_SELECTED]: 'All selected',

  // Change Password Placeholders
  [StringKey.ENTER_CURRENT_PASSWORD]: 'Enter current password',
  [StringKey.PASSWORD_MIN_HINT]: 'Min. 8 characters',
  [StringKey.REPEAT_NEW_PASSWORD]: 'Repeat new password',

  // Brand Images
  [StringKey.BRANDING]: 'Branding',
  [StringKey.BRAND_IMAGES]: 'Brand Images',
  [StringKey.LOGO_URL]: 'Logo URL',
  [StringKey.BANNER_URL]: 'Banner URL',

  // Settings Page (additional)
  [StringKey.YOUR_ESTABLISHMENT]: 'Your establishment',
  [StringKey.ESTABLISHMENT_PROFILE]: 'Establishment Profile',
  [StringKey.ESTABLISHMENT_PROFILE_DESCRIPTION]:
    'Manage how your establishment appears to customers on Nom Nom Save.',
  [StringKey.BASIC_INFORMATION]: 'Basic information',
  [StringKey.GENERAL_DETAILS]: 'General Details',
  [StringKey.ESTABLISHMENT_NAME]: 'Establishment name',
  [StringKey.CONTACT_EMAIL]: 'Contact email',
  [StringKey.LOCATION]: 'Location',
  [StringKey.ADDRESS_AND_MAP]: 'Address & Map',
  [StringKey.STREET_ADDRESS]: 'Street address',
  [StringKey.LATITUDE]: 'Latitude',
  [StringKey.LONGITUDE]: 'Longitude',
  [StringKey.SCHEDULE]: 'Schedule',
  [StringKey.SECURITY]: 'Security',
  [StringKey.UPDATE_PASSWORD]: 'Update password',
  [StringKey.DANGER_ZONE]: 'Danger zone',
  [StringKey.DELETE_ESTABLISHMENT]: 'Delete establishment',
  [StringKey.DELETE_ESTABLISHMENT_WARNING]:
    'Permanently delete your establishment and all associated data. This action cannot be undone.',
  [StringKey.PREVIEW]: 'Preview',
  [StringKey.HOW_CUSTOMERS_SEE_YOU]: 'How customers see you',
  [StringKey.IMPACT]: 'Impact',
  [StringKey.YOUR_IMPACT_TOGETHER]: 'Your Impact Together',
  [StringKey.UNSAVED_CHANGES]: 'Unsaved changes',
  [StringKey.DISCARD]: 'Discard',

  // Multi-select (Product/Box dialogs)
  [StringKey.ALLERGENS]: 'Allergens',
  [StringKey.SELECT_ALLERGENS]: 'Select allergens…',
  [StringKey.SELECT_TYPES]: 'Select types…',
  [StringKey.SELECT_PRODUCTS]: 'Select products…',
  [StringKey.PRODUCTS_IN_BOX]: 'Products in box',
  [StringKey.DERIVED_ALLERGENS]: 'Allergens (from products)',
  [StringKey.NO_TYPES_AVAILABLE]: 'No types available',
  [StringKey.NO_ALLERGENS_AVAILABLE]: 'No allergens available',
  [StringKey.NO_PRODUCTS_AVAILABLE]: 'No products available',
  [StringKey.WEIGHT]: 'Weight (g)',
  [StringKey.PICTURE_URL]: 'Image URL',
  [StringKey.QUANTITY_OF_ITEMS]: 'Items in box',

  // Analytics
  [StringKey.ANALYTICS_TITLE]: 'Analytics',
  [StringKey.ANALYTICS_COMING_SOON]:
    'Analytics dashboard is coming soon. Track your sales, impact, and customer trends here.',

  // Header
  [StringKey.NOM_NOM_SAVE]: 'Nom Nom Save',
  [StringKey.LOG_IN]: 'Log In',
  [StringKey.SING_IN]: 'Sing In',
  [StringKey.DASHBOARD]: 'Dashboard',
  [StringKey.MAP]: 'Map',

  // Landing
  [StringKey.GOOD_FOOD]: 'Good Food',
  [StringKey.GREAT_PRICES]: 'Great Prices',
  [StringKey.RESCUE_FOOD_DESCRIPTION]:
    "Rescue delicious unsold food from local favorites. It's an easy way to eat well, save money, and help the planet.",
  [StringKey.NOM_NOM]: 'Nom Nom',
  [StringKey.SAVE]: 'Save',
  [StringKey.ON_THE_GO]: 'on the go',
  [StringKey.MOBILE_PROMO_DESCRIPTION]:
    'Get real-time alerts for local food drops and claim your bags in seconds.',
  [StringKey.GOOGLE_PLAY]: 'Google Play',
  [StringKey.GET_IN_ON]: 'GET IT ON',
  [StringKey.HOW_IT_WORKS]: 'How It Works',
  [StringKey.SUSTAINABLE_EATING]: 'Sustainable eating, simplified.',
  [StringKey.BROWSE_OFFERS]: 'Browse Offers',
  [StringKey.BROWSE_OFFERS_DESCRIPTION]:
    'Find local shops near you with surplus food ready to be rescued at up to 70% off.',
  [StringKey.RESERVE_BAG]: 'Reserve Bag',
  [StringKey.RESERVE_BAG_DESCRIPTION]:
    'Select a "Magic Bag" filled with delicious mystery treats and confirm your pickup.',
  [StringKey.PICK_UP_AND_SAVE]: 'Pick up & Save',
  [StringKey.PICK_UP_AND_SAVE_DESCRIPTION]:
    'Stop by at the designated time, show your receipt, and enjoy your amazing food.',
  [StringKey.AVAILABLE_NOW]: 'Available Now',
  [StringKey.FRESHLY_LISTED]: 'Freshly listed surplus near you.',
  [StringKey.NO_ESTABLISHMENTS_NEARBY]: 'No establishments nearby',
  [StringKey.EXPLORE_ALL]: 'Explore All',

  // User Profile
  [StringKey.PREMIUM]: 'Premium',
  [StringKey.UNLOCK_PREMIUM]: 'Unlock Premium',
  [StringKey.SUBSCRIPTION_ACTIVE_THANK_YOU]: 'Thank you for supporting our mission',
  [StringKey.PLAN_EXPIRES]: 'Plan expires',

  // Subscription Plans Page
  [StringKey.SUBSCRIPTION_PLANS]: 'Subscription Plans',
  [StringKey.SUBSCRIPTION_PLANS_TITLE]: 'Choose your plan',
  [StringKey.SUBSCRIPTION_PLANS_SUBTITLE]:
    "Whether you're saving food or selling surplus — there's a plan for you.",
  [StringKey.PLAN_FREE_NAME]: 'Free',
  [StringKey.PLAN_SPONSOR_NAME]: 'Sponsor',
  [StringKey.PLAN_PREMIUM_NAME]: 'Premium',
  [StringKey.PLAN_PRO_NAME]: 'Pro',
  [StringKey.SUBSCRIBE_WITH_PAYPAL]: 'Subscribe with PayPal',
  [StringKey.CURRENT_PLAN_BTN]: 'Current Plan',
  [StringKey.MANAGE_SUBSCRIPTION]: 'Manage Subscription',
  [StringKey.CANCEL_SUBSCRIPTION]: 'Cancel Subscription',
  [StringKey.CANCEL_SUBSCRIPTION_CONFIRM_TITLE]: 'Cancel your subscription?',
  [StringKey.CANCEL_SUBSCRIPTION_CONFIRM_DESC]:
    'Your plan will be cancelled immediately. You will lose access to premium features.',
  [StringKey.SUBSCRIPTION_CANCELLED]: 'Subscription cancelled',
  [StringKey.FAILED_TO_CANCEL_SUBSCRIPTION]: 'Failed to cancel subscription',
  [StringKey.CURRENT_PLAN_BADGE]: 'Current plan',
  [StringKey.FREE_FOREVER]: '$0 / forever',
  [StringKey.PER_MONTH]: '/ month',
  [StringKey.PER_DAY]: '/ day',
  [StringKey.FREE_PLAN_FEAT_1]: 'Browse all local offers',
  [StringKey.FREE_PLAN_FEAT_2]: 'Standard map access',
  [StringKey.FREE_PLAN_FEAT_3]: 'Basic order history',
  [StringKey.SPONSOR_PLAN_FEAT_1]: 'Everything in Premium',
  [StringKey.SPONSOR_PLAN_FEAT_2]: 'Dedicated support',
  [StringKey.SPONSOR_PLAN_FEAT_3]: 'Early access to new features',

  [StringKey.BUYER_FREE_DESCRIPTION]: 'Start discovering surplus food near you at no cost.',
  [StringKey.BUYER_FREE_FEAT_1]: 'Browse offers list & feed',
  [StringKey.BUYER_FREE_FEAT_2]: 'Order & collect with QR code',
  [StringKey.BUYER_FREE_FEAT_3]: 'Order history & reviews',
  [StringKey.BUYER_FREE_LOCKED_1]: 'Real-time map',
  [StringKey.BUYER_FREE_LOCKED_2]: 'Early access to boxes',
  [StringKey.BUYER_FREE_LOCKED_3]: 'Personalised notifications',

  [StringKey.BUYER_PREMIUM_DESCRIPTION]: 'Get the full experience — find deals before anyone else.',
  [StringKey.BUYER_PREMIUM_FEAT_1]: 'Everything in Free',
  [StringKey.BUYER_PREMIUM_FEAT_2]: 'Real-time map with live offers',
  [StringKey.BUYER_PREMIUM_FEAT_3]: 'Early access to boxes before public',
  [StringKey.BUYER_PREMIUM_FEAT_4]: 'Personalised push notifications',
  [StringKey.BUYER_PREMIUM_FEAT_5]: 'Priority customer support',

  [StringKey.BUYER_SPONSOR_DESCRIPTION]:
    'Ultimate access with exclusive perks and priority service.',
  [StringKey.BUYER_SPONSOR_FEAT_1]: 'Everything in Premium',
  [StringKey.BUYER_SPONSOR_FEAT_2]: 'Exclusive boxes first',
  [StringKey.BUYER_SPONSOR_FEAT_3]: 'Personal shopper assistant',
  [StringKey.BUYER_SPONSOR_FEAT_4]: 'Sponsor badge on profile',
  [StringKey.BUYER_SPONSOR_FEAT_5]: 'Dedicated support',

  [StringKey.EST_FREE_DESCRIPTION]: 'Start selling surplus with basic tools at no cost.',
  [StringKey.EST_FREE_FEAT_1]: 'Up to 5 active boxes at once',
  [StringKey.EST_FREE_FEAT_2]: 'Basic order management',
  [StringKey.EST_FREE_FEAT_3]: 'QR code pickup system',
  [StringKey.EST_FREE_LOCKED_1]: 'Unlimited active offers',
  [StringKey.EST_FREE_LOCKED_2]: 'Advanced analytics',
  [StringKey.EST_FREE_LOCKED_3]: 'Offer templates',
  [StringKey.EST_FREE_LOCKED_4]: 'Map promotion',

  [StringKey.EST_PRO_DESCRIPTION]: 'Scale your surplus sales with powerful tools and analytics.',
  [StringKey.EST_PRO_FEAT_1]: 'Everything in Free',
  [StringKey.EST_PRO_FEAT_2]: 'Unlimited active offers',
  [StringKey.EST_PRO_FEAT_3]: 'Advanced analytics dashboard',
  [StringKey.EST_PRO_FEAT_4]: 'Offer templates & scheduling',
  [StringKey.EST_PRO_FEAT_5]: 'Map promotion for your listing',
  [StringKey.EST_PRO_LOCKED_1]: 'Priority search ranking',
  [StringKey.EST_PRO_LOCKED_2]: 'Promoted individual offers',

  [StringKey.EST_SPONSOR_DESCRIPTION]: 'Maximum visibility and impact for your establishment.',
  [StringKey.EST_SPONSOR_FEAT_1]: 'Everything in Pro',
  [StringKey.EST_SPONSOR_FEAT_2]: 'Priority ranking in search & feed',
  [StringKey.EST_SPONSOR_FEAT_3]: 'Promoted offers highlighted to buyers',
  [StringKey.EST_SPONSOR_FEAT_4]: 'Sponsor badge on your profile',
  [StringKey.EST_SPONSOR_FEAT_5]: 'Dedicated account support',
  [StringKey.EST_SPONSOR_FEAT_6]: 'Early access to new features',

  [StringKey.TRUST_SECURE_PAYMENTS]: 'Secure PayPal payments',
  [StringKey.TRUST_CANCEL_ANYTIME]: 'Cancel anytime',
  [StringKey.TRUST_AUTO_RENEWS]: 'Auto-renews monthly',
  [StringKey.TRUST_ZERO_WASTE]: 'Supporting zero food waste',

  [StringKey.FAQ_TITLE]: 'Frequently Asked Questions',
  [StringKey.FAQ_1_Q]: 'Can I cancel my subscription anytime?',
  [StringKey.FAQ_1_A]:
    'Yes, you can cancel at any time through PayPal. Your plan stays active until the end of the current billing period.',
  [StringKey.FAQ_2_Q]: 'How does billing work?',
  [StringKey.FAQ_2_A]:
    'Billing is handled entirely through PayPal. You will be charged monthly on the same date you subscribed.',
  [StringKey.FAQ_3_Q]: 'Can I upgrade my plan?',
  [StringKey.FAQ_3_A]:
    'Yes. Cancel your current plan through PayPal and subscribe to the new plan. The upgrade takes effect immediately.',
  [StringKey.FAQ_4_Q]: 'What happens if I exceed 5 boxes on the Free plan?',
  [StringKey.FAQ_4_A]:
    'You will need to deactivate or remove an existing active box before publishing a new one. Upgrading to Pro removes this limit.',

  // Complete / Cancel Subscription Pages
  [StringKey.CONFIRMING_SUBSCRIPTION]: 'Confirming your subscription…',
  [StringKey.PAYMENT_SUCCESSFUL_BADGE]: 'Payment successful',
  [StringKey.YOU_ARE_ALL_SET]: "You're all set!",
  [StringKey.SUBSCRIPTION_ACTIVATED_DESC]:
    'Your subscription has been activated. Welcome to the premium experience on Nom Nom Save.',
  [StringKey.MONTHLY_RENEWS]: 'Monthly · renews automatically',
  [StringKey.NEXT_BILLING_DATE]: 'Next billing date:',
  [StringKey.WHAT_YOU_UNLOCKED]: 'What you unlocked',
  [StringKey.GO_TO_DASHBOARD]: 'Go to Dashboard',
  [StringKey.VIEW_MY_PLAN]: 'View my plan',
  [StringKey.PAYMENT_CANCELLED_BADGE]: 'Payment cancelled',
  [StringKey.NO_CHARGE_MADE]: 'No charge was made',
  [StringKey.PAYMENT_CANCELLED_DESC]:
    'You cancelled the payment process. Your account has not been charged and you remain on your current plan.',
  [StringKey.YOU_STILL_HAVE_ACCESS]: 'You still have access to',
  [StringKey.CANCEL_SUB_LOCKED_ITEM]: 'Real-time map, early access & more — upgrade to unlock',
  [StringKey.STILL_THINKING]: 'Still thinking about it?',
  [StringKey.UPSELL_DESC]: 'Premium starts at just $4.99/month. Cancel anytime, no commitments.',
  [StringKey.SEE_PLANS_AGAIN]: 'See plans again',

  [StringKey.MEMBER_SINCE]: 'Member since',
  [StringKey.ORDERS]: 'Orders',
  [StringKey.SAVED]: 'Saved',
  [StringKey.PROFILE_SETTINGS]: 'Profile Settings',
  [StringKey.PROFILE_SETTINGS_DESCRIPTION]:
    'Manage your personal information, address, and account preferences to keep your Nom Nom Sav experience running smoothly.',
  [StringKey.PERSONAL_DETAILS]: 'Personal Details',
  [StringKey.NOTIFY_NEARBY]: 'Notify me about nearby establishments',
  [StringKey.NOTIFY_CLOSING_SOON]: 'Notify me when establishments are closing soon',
  [StringKey.NOTIFY_NEW_ITEMS]: 'Notify me about new items',
  [StringKey.MY_ORDERS]: 'My Orders',
  [StringKey.FAVORITES]: 'Favorites',
  [StringKey.PAYMENT_METHODS]: 'Payment Methods',
  [StringKey.PROFILE]: 'Profile',

  // User Orders
  [StringKey.TOTAL_ORDERS]: 'Total Orders',
  [StringKey.MONEY_SAVED]: 'Money Saved',
  [StringKey.WASTE_PREVENTED]: 'Waste Prevented',
  [StringKey.UPCOMING_ORDERS]: 'Upcoming Orders',
  [StringKey.COMPLETED_ORDERS]: 'Completed Orders',
  [StringKey.NO_UPCOMING_ORDERS]: 'No Upcoming Orders',
  [StringKey.PICKUP]: 'Pickup',
  [StringKey.SHOW_QR]: 'Show QR',
  [StringKey.EXPIRED]: 'Expired',
  [StringKey.ORDER_CANCELED]: 'Order cancelled successfully!',
  [StringKey.FAILED_TO_CANCEL_ORDER]: 'Failed to cancel order',
  [StringKey.PRICE]: 'Price',
  [StringKey.CANCEL_ORDER]: 'Cancel Order',
  [StringKey.SURE_TO_CANCEL_ORDER]: 'Are you sure you want to cancel this order?',
  [StringKey.COMPLETED]: 'Completed',
  [StringKey.PICKED_UP]: 'Picked up',
  [StringKey.NO_COMPLETED_ORDERS]: 'No Completed Orders',
  [StringKey.CANCELLED_OR_EXPIRED_ORDERS]: 'Cancelled or Expired Orders',
  [StringKey.CANCELLED]: 'Cancelled',
  [StringKey.NO_CANCELLED_OR_EXPIRED_ORDERS]: 'No Cancelled or Expired Orders',
  [StringKey.QR_CODE]: 'QR Code',

  // Favorites
  [StringKey.YOUR_SAVED_ESTABLISHMENTS]: 'Your saved establishments',
  [StringKey.PLACES]: 'places',
  [StringKey.ADDED]: 'Added',
  [StringKey.VIEW]: 'View',
  [StringKey.NO_FAVORITES_ESTABLISHMENTS]: 'No favorite establishments',
  [StringKey.SUCCESSFULLY_REMOVED_FROM_FAVORITES]:
    'Successfully removed {establishmentName} from favorites',
  [StringKey.FAILED_TO_REMOVE_FROM_FAVORITES]:
    'Failed to remove {establishmentName} from favorites',
  [StringKey.REMOVE_FROM_FAVORITES]: 'Remove from favorites',
  [StringKey.SURE_YOU_WANT_TO_REMOVE_FROM_FAVORITES]:
    'Are you sure you want to remove {establishmentName} from favorites?',
  [StringKey.REMOVE]: 'Remove',
  [StringKey.REMOVING]: 'Removing',
  [StringKey.SUCCESSFULLY_ADDED_TO_FAVORITES]:
    'Successfully added {establishmentName} to favorites',
  [StringKey.FAILED_TO_ADD_TO_FAVORITES]: 'Failed to add {establishmentName} to favorites',

  // Public Establishment Profile
  [StringKey.VIEW_MENU]: 'View Menu',
  [StringKey.OPEN_NOW]: 'OPEN NOW',
  [StringKey.ABOUT]: 'About',
  [StringKey.IMPACT_TOGETHER]: 'Impact Together',
  [StringKey.REVIEWS]: 'reviews',
  [StringKey.WRITE_A_REVIEW]: 'Write a review',
  [StringKey.NO_REVIEWS_YET]: 'No reviews yet',
  [StringKey.ONE_DAY_AGO]: '1 day ago',
  [StringKey.DAYS_AGO]: '{{count}} days ago',
  [StringKey.MONTHS_AGO]: '{{count}} months ago',
  [StringKey.YEARS_AGO]: '{{count}} years ago',
  [StringKey.ADD_TO_CART]: 'Add to cart',
  [StringKey.LOAD_MORE]: 'Load more',
  [StringKey.LOADING]: 'Loading…',
  [StringKey.ACTIVE_OFFERS]: 'Active Offers',
  [StringKey.LIVE]: 'Live',
  [StringKey.NO_ACTIVE_OFFERS]: 'No active offers',
  [StringKey.NO_ACTIVE_OFFERS_DESCRIPTION]:
    'This establishment has no items available right now. Check back later!',
  [StringKey.SHARE_ESTABLISHMENT]: 'Share establishment',
  [StringKey.LINK_COPIED]: 'Link Copied',
  [StringKey.FAILED_TO_COPY_LINK]: 'Failed to copy link',
  [StringKey.COPY]: 'Copy',
  [StringKey.COPIED]: 'Copied',
  [StringKey.BACK_TO_REVIEWS]: 'Back to reviews',
  [StringKey.COMMENT]: 'Comment',
  [StringKey.COMMENT_MIN]: 'Comment must be at least 10 characters',
  [StringKey.COMMENT_MAX]: 'Comment must be less or equal 500 characters',
  [StringKey.RATING_REQUIRED]: 'Rating is required',
  [StringKey.SELECT_RATING]: 'Select rating',
  [StringKey.REVIEW_SUBMITTED]: 'Review submitted successfully!',
  [StringKey.REVIEW_FAILED]: 'Failed to create review',
  [StringKey.SUBMIT_REVIEW]: 'Submit review',
  [StringKey.REVIEW_UPDATED]: 'Review successfully updated',
  [StringKey.REVIEW_DELETED]: 'Review deleted',
  [StringKey.CAN_EDIT_UNTIL]: 'Can edit until: {{time}}',
  [StringKey.EDITING_YOUR_REVIEW]: 'Editing your review',
  [StringKey.YOU]: 'You',
  [StringKey.NEW_REVIEW_AFTER_EDIT_EXPIRES]: 'You can leave a new review after this period expires',
  [StringKey.DELETE_YOUR_REVIEW]: 'Delete your review',
  [StringKey.SURE_YOU_WANT_TO_DELETE_REVIEW]: 'Are you sure you want to delete this review?',
  [StringKey.LOGIN_TO_SEE_YOUR_REVIEWS]: 'Login to see your reviews',
  [StringKey.YOU_HAVE_NO_REVIEWS]: 'You have no reviews',
  [StringKey.VISIT_ESTABLISHMENTS_TO_REVIEW]: 'Visit establishments to review',
  [StringKey.ALL_REVIEWS]: 'All reviews',
  [StringKey.MY_REVIEWS]: 'My reviews',
  [StringKey.NEWEST_FIRST]: 'Newest first',
  [StringKey.OLDEST_FIRST]: 'Oldest first',
  [StringKey.FILTER]: 'Filter',
  [StringKey.ALL]: 'All',
  [StringKey.NO_REVIEWS_FOR_RATING]: "You haven't left any {{rating}}-star reviews",

  // Establishments List
  [StringKey.NO_ESTABLISHMENTS]: 'No establishments found',
  [StringKey.NO_ESTABLISHMENTS_DESCRIPTION]:
    'There are no establishments available at the moment. Please check back later',
  [StringKey.DISTANCE]: 'Distance',
  [StringKey.ANY]: 'Any',
  [StringKey.MIN_RATING]: 'Min Rating',
  [StringKey.RATING]: 'Rating',
  [StringKey.CLOSING_TIME]: 'Closing time',
  [StringKey.SORT_BY]: 'Sort by',
  [StringKey.SORT_ORDER]: 'Sort order',
  [StringKey.CLOSEST_FIRST]: 'Closest first',
  [StringKey.FURTHEST_FIRST]: 'Furthest first',
  [StringKey.HIGHEST_RATED]: 'Highest rating first',
  [StringKey.LOWEST_RATED]: 'Lowest rating first',
  [StringKey.CLOSING_SOONEST]: 'Closing soonest',
  [StringKey.CLOSING_LATEST]: 'Closing latest',
  [StringKey.CITY]: 'City',
  [StringKey.ALL_CITIES]: 'All cities',
  [StringKey.MY_LOCATION]: 'My location',
  [StringKey.SELECTED]: 'Selected',
  [StringKey.PRODUCT_TYPES]: 'Product types',
  [StringKey.SEARCH_TYPE]: 'Search type',
  [StringKey.VIEW_ALL]: 'View all',
  [StringKey.NO_TYPE_FOUND]: 'No type found.',
  [StringKey.CLOSED_TODAY]: 'Closed today',
  [StringKey.PUBLISH_UNAVAILABLE_CLOSED_DAY]:
    'Publishing is unavailable — your establishment is closed today. Update your working hours in Settings to enable publishing.',
  [StringKey.ITEMS_LEFT]: 'left',

  // Cart
  [StringKey.HOW_MANY]: 'How many?',
  [StringKey.MY_CART]: 'My Cart',
  [StringKey.CART_EMPTY]: 'Your cart is empty.',
  [StringKey.CART_ESTABLISHMENTS_COUNT]: 'You have items from {{count}} establishments',
  [StringKey.GO_TO_ORDER]: 'Go to order',
  [StringKey.BACK_TO_CART]: 'Back to cart',
  [StringKey.ORDER_SUMMARY]: 'Order Summary',
  [StringKey.PLACE_ORDER]: 'Place Order',
  [StringKey.REMOVE_FROM_CART]: 'Remove from cart',
  [StringKey.SURE_YOU_WANT_TO_REMOVE_FROM_CART]: 'Are you sure you want to remove from cart?',
  [StringKey.ORDER_PLACED_SUCCESS]: 'Your order has been placed successfully!',
  [StringKey.ORDER_PLACED_ERROR]: 'Failed to place order. Please try again.',
  [StringKey.PLACING_ORDER]: 'Placing order...',
  [StringKey.TOTAL]: 'Total',
  [StringKey.ORDER_NOT_ENOUGH_QUANTITY]: 'Not enough quantity for item',
  [StringKey.MAX_QUANTITY_REACHED]: 'Maximum quantity reached',
  [StringKey.ALREADY_MAX_IN_CART]: 'You already have the maximum available quantity in your cart',
  [StringKey.ADDED_TO_CART]: 'Added to cart',
  [StringKey.NO_MORE_AVAILABLE]: 'No more items available',
};
