export enum QueryKey {
  FAVORITES = 'FAVORITES',
  ESTABLISHMENT = 'ESTABLISHMENT',
  ESTABLISHMENT_REVIEWS = 'ESTABLISHMENT_REVIEWS',
  MENU = 'MENU',
  USER_REVIEWS = 'USER_REVIEWS',
  ESTABLISHMENT_REVIEWS_DISTRIBUTION = 'ESTABLISHMENT_REVIEWS_DISTRIBUTION',
  ESTABLISHMENTS = 'ESTABLISHMENTS',
  ESTABLISHMENTS_CITIES = 'ESTABLISHMENTS_CITIES',
}
