/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompleteSubscriptionRouteImport } from './routes/complete-subscription'
import { Route as CancelSubscriptionRouteImport } from './routes/cancel-subscription'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UserRouteImport } from './routes/_user'
import { Route as EstablishmentRouteImport } from './routes/_establishment'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsPlansRouteImport } from './routes/subscriptions.plans'
import { Route as EstablishmentsEstablishmentIdRouteImport } from './routes/establishments.$establishmentId'
import { Route as UserProfileRouteImport } from './routes/_user.profile'
import { Route as UserMapRouteImport } from './routes/_user.map'
import { Route as UserHowItWorksRouteImport } from './routes/_user.how-it-works'
import { Route as UserDashboardRouteImport } from './routes/_user.dashboard'
import { Route as EstablishmentTemplatesRouteImport } from './routes/_establishment.templates'
import { Route as EstablishmentSettingsRouteImport } from './routes/_establishment.settings'
import { Route as EstablishmentMenuRouteImport } from './routes/_establishment.menu'
import { Route as EstablishmentAnalyticsRouteImport } from './routes/_establishment.analytics'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as UserProfileSettingsRouteImport } from './routes/_user.profile.settings'
import { Route as UserProfilePaymentMethodsRouteImport } from './routes/_user.profile.payment-methods'
import { Route as UserProfileOrdersRouteImport } from './routes/_user.profile.orders'
import { Route as UserProfileFavoritesRouteImport } from './routes/_user.profile.favorites'

const CompleteSubscriptionRoute = CompleteSubscriptionRouteImport.update({
  id: '/complete-subscription',
  path: '/complete-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelSubscriptionRoute = CancelSubscriptionRouteImport.update({
  id: '/cancel-subscription',
  path: '/cancel-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const EstablishmentRoute = EstablishmentRouteImport.update({
  id: '/_establishment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsPlansRoute = SubscriptionsPlansRouteImport.update({
  id: '/subscriptions/plans',
  path: '/subscriptions/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const EstablishmentsEstablishmentIdRoute =
  EstablishmentsEstablishmentIdRouteImport.update({
    id: '/establishments/$establishmentId',
    path: '/establishments/$establishmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserMapRoute = UserMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => UserRoute,
} as any)
const UserHowItWorksRoute = UserHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const EstablishmentTemplatesRoute = EstablishmentTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => EstablishmentRoute,
} as any)
const EstablishmentSettingsRoute = EstablishmentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EstablishmentRoute,
} as any)
const EstablishmentMenuRoute = EstablishmentMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => EstablishmentRoute,
} as any)
const EstablishmentAnalyticsRoute = EstablishmentAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => EstablishmentRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const UserProfileSettingsRoute = UserProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserProfileRoute,
} as any)
const UserProfilePaymentMethodsRoute =
  UserProfilePaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => UserProfileRoute,
  } as any)
const UserProfileOrdersRoute = UserProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => UserProfileRoute,
} as any)
const UserProfileFavoritesRoute = UserProfileFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => UserProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancel-subscription': typeof CancelSubscriptionRoute
  '/complete-subscription': typeof CompleteSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/analytics': typeof EstablishmentAnalyticsRoute
  '/menu': typeof EstablishmentMenuRoute
  '/settings': typeof EstablishmentSettingsRoute
  '/templates': typeof EstablishmentTemplatesRoute
  '/dashboard': typeof UserDashboardRoute
  '/how-it-works': typeof UserHowItWorksRoute
  '/map': typeof UserMapRoute
  '/profile': typeof UserProfileRouteWithChildren
  '/establishments/$establishmentId': typeof EstablishmentsEstablishmentIdRoute
  '/subscriptions/plans': typeof SubscriptionsPlansRoute
  '/profile/favorites': typeof UserProfileFavoritesRoute
  '/profile/orders': typeof UserProfileOrdersRoute
  '/profile/payment-methods': typeof UserProfilePaymentMethodsRoute
  '/profile/settings': typeof UserProfileSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancel-subscription': typeof CancelSubscriptionRoute
  '/complete-subscription': typeof CompleteSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/analytics': typeof EstablishmentAnalyticsRoute
  '/menu': typeof EstablishmentMenuRoute
  '/settings': typeof EstablishmentSettingsRoute
  '/templates': typeof EstablishmentTemplatesRoute
  '/dashboard': typeof UserDashboardRoute
  '/how-it-works': typeof UserHowItWorksRoute
  '/map': typeof UserMapRoute
  '/profile': typeof UserProfileRouteWithChildren
  '/establishments/$establishmentId': typeof EstablishmentsEstablishmentIdRoute
  '/subscriptions/plans': typeof SubscriptionsPlansRoute
  '/profile/favorites': typeof UserProfileFavoritesRoute
  '/profile/orders': typeof UserProfileOrdersRoute
  '/profile/payment-methods': typeof UserProfilePaymentMethodsRoute
  '/profile/settings': typeof UserProfileSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_establishment': typeof EstablishmentRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/about': typeof AboutRoute
  '/cancel-subscription': typeof CancelSubscriptionRoute
  '/complete-subscription': typeof CompleteSubscriptionRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_establishment/analytics': typeof EstablishmentAnalyticsRoute
  '/_establishment/menu': typeof EstablishmentMenuRoute
  '/_establishment/settings': typeof EstablishmentSettingsRoute
  '/_establishment/templates': typeof EstablishmentTemplatesRoute
  '/_user/dashboard': typeof UserDashboardRoute
  '/_user/how-it-works': typeof UserHowItWorksRoute
  '/_user/map': typeof UserMapRoute
  '/_user/profile': typeof UserProfileRouteWithChildren
  '/establishments/$establishmentId': typeof EstablishmentsEstablishmentIdRoute
  '/subscriptions/plans': typeof SubscriptionsPlansRoute
  '/_user/profile/favorites': typeof UserProfileFavoritesRoute
  '/_user/profile/orders': typeof UserProfileOrdersRoute
  '/_user/profile/payment-methods': typeof UserProfilePaymentMethodsRoute
  '/_user/profile/settings': typeof UserProfileSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cancel-subscription'
    | '/complete-subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/analytics'
    | '/menu'
    | '/settings'
    | '/templates'
    | '/dashboard'
    | '/how-it-works'
    | '/map'
    | '/profile'
    | '/establishments/$establishmentId'
    | '/subscriptions/plans'
    | '/profile/favorites'
    | '/profile/orders'
    | '/profile/payment-methods'
    | '/profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cancel-subscription'
    | '/complete-subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/analytics'
    | '/menu'
    | '/settings'
    | '/templates'
    | '/dashboard'
    | '/how-it-works'
    | '/map'
    | '/profile'
    | '/establishments/$establishmentId'
    | '/subscriptions/plans'
    | '/profile/favorites'
    | '/profile/orders'
    | '/profile/payment-methods'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_establishment'
    | '/_user'
    | '/about'
    | '/cancel-subscription'
    | '/complete-subscription'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_establishment/analytics'
    | '/_establishment/menu'
    | '/_establishment/settings'
    | '/_establishment/templates'
    | '/_user/dashboard'
    | '/_user/how-it-works'
    | '/_user/map'
    | '/_user/profile'
    | '/establishments/$establishmentId'
    | '/subscriptions/plans'
    | '/_user/profile/favorites'
    | '/_user/profile/orders'
    | '/_user/profile/payment-methods'
    | '/_user/profile/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  EstablishmentRoute: typeof EstablishmentRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AboutRoute: typeof AboutRoute
  CancelSubscriptionRoute: typeof CancelSubscriptionRoute
  CompleteSubscriptionRoute: typeof CompleteSubscriptionRoute
  EstablishmentsEstablishmentIdRoute: typeof EstablishmentsEstablishmentIdRoute
  SubscriptionsPlansRoute: typeof SubscriptionsPlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complete-subscription': {
      id: '/complete-subscription'
      path: '/complete-subscription'
      fullPath: '/complete-subscription'
      preLoaderRoute: typeof CompleteSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel-subscription': {
      id: '/cancel-subscription'
      path: '/cancel-subscription'
      fullPath: '/cancel-subscription'
      preLoaderRoute: typeof CancelSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_establishment': {
      id: '/_establishment'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof EstablishmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/plans': {
      id: '/subscriptions/plans'
      path: '/subscriptions/plans'
      fullPath: '/subscriptions/plans'
      preLoaderRoute: typeof SubscriptionsPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/establishments/$establishmentId': {
      id: '/establishments/$establishmentId'
      path: '/establishments/$establishmentId'
      fullPath: '/establishments/$establishmentId'
      preLoaderRoute: typeof EstablishmentsEstablishmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/map': {
      id: '/_user/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof UserMapRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/how-it-works': {
      id: '/_user/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof UserHowItWorksRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/dashboard': {
      id: '/_user/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/_establishment/templates': {
      id: '/_establishment/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof EstablishmentTemplatesRouteImport
      parentRoute: typeof EstablishmentRoute
    }
    '/_establishment/settings': {
      id: '/_establishment/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof EstablishmentSettingsRouteImport
      parentRoute: typeof EstablishmentRoute
    }
    '/_establishment/menu': {
      id: '/_establishment/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof EstablishmentMenuRouteImport
      parentRoute: typeof EstablishmentRoute
    }
    '/_establishment/analytics': {
      id: '/_establishment/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof EstablishmentAnalyticsRouteImport
      parentRoute: typeof EstablishmentRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_user/profile/settings': {
      id: '/_user/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof UserProfileSettingsRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/profile/payment-methods': {
      id: '/_user/profile/payment-methods'
      path: '/payment-methods'
      fullPath: '/profile/payment-methods'
      preLoaderRoute: typeof UserProfilePaymentMethodsRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/profile/orders': {
      id: '/_user/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof UserProfileOrdersRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/profile/favorites': {
      id: '/_user/profile/favorites'
      path: '/favorites'
      fullPath: '/profile/favorites'
      preLoaderRoute: typeof UserProfileFavoritesRouteImport
      parentRoute: typeof UserProfileRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EstablishmentRouteChildren {
  EstablishmentAnalyticsRoute: typeof EstablishmentAnalyticsRoute
  EstablishmentMenuRoute: typeof EstablishmentMenuRoute
  EstablishmentSettingsRoute: typeof EstablishmentSettingsRoute
  EstablishmentTemplatesRoute: typeof EstablishmentTemplatesRoute
}

const EstablishmentRouteChildren: EstablishmentRouteChildren = {
  EstablishmentAnalyticsRoute: EstablishmentAnalyticsRoute,
  EstablishmentMenuRoute: EstablishmentMenuRoute,
  EstablishmentSettingsRoute: EstablishmentSettingsRoute,
  EstablishmentTemplatesRoute: EstablishmentTemplatesRoute,
}

const EstablishmentRouteWithChildren = EstablishmentRoute._addFileChildren(
  EstablishmentRouteChildren,
)

interface UserProfileRouteChildren {
  UserProfileFavoritesRoute: typeof UserProfileFavoritesRoute
  UserProfileOrdersRoute: typeof UserProfileOrdersRoute
  UserProfilePaymentMethodsRoute: typeof UserProfilePaymentMethodsRoute
  UserProfileSettingsRoute: typeof UserProfileSettingsRoute
}

const UserProfileRouteChildren: UserProfileRouteChildren = {
  UserProfileFavoritesRoute: UserProfileFavoritesRoute,
  UserProfileOrdersRoute: UserProfileOrdersRoute,
  UserProfilePaymentMethodsRoute: UserProfilePaymentMethodsRoute,
  UserProfileSettingsRoute: UserProfileSettingsRoute,
}

const UserProfileRouteWithChildren = UserProfileRoute._addFileChildren(
  UserProfileRouteChildren,
)

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserHowItWorksRoute: typeof UserHowItWorksRoute
  UserMapRoute: typeof UserMapRoute
  UserProfileRoute: typeof UserProfileRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserHowItWorksRoute: UserHowItWorksRoute,
  UserMapRoute: UserMapRoute,
  UserProfileRoute: UserProfileRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  EstablishmentRoute: EstablishmentRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AboutRoute: AboutRoute,
  CancelSubscriptionRoute: CancelSubscriptionRoute,
  CompleteSubscriptionRoute: CompleteSubscriptionRoute,
  EstablishmentsEstablishmentIdRoute: EstablishmentsEstablishmentIdRoute,
  SubscriptionsPlansRoute: SubscriptionsPlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
